#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

main = "producer.ts"
name = "producer"

[[services]]
binding = "publish"
service = "publish"
