#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

main = "bus.ts"
name = "bus"

services = [
  { binding = "subscriber", service = "subscriber", entrypoint = "subscriber" }
]
