#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

main = "publisher.ts"
name = "publisher"

services = [
  { binding = "bus", service = "bus", entrypoint = "bus" }
]
